
services:
  postgres:
    image: postgres:17
    container_name: hemut_postgres
    restart: always
    env_file:
      - ./envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: hemut_backend
    build:
      context: ./backend
    command: >
      uvicorn run:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - ./envs/backend.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  # frontend:
  #   container_name: hemut_frontend
  #   build:
  #     context: ./frontend
  #   command: npm run dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
